# Generated by Django 5.0.6 on 2024-05-25 16:01

import artist.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[(artist.models.GenderEnum['MALE'], 'M'), (artist.models.GenderEnum['FEMALE'], 'F'), (artist.models.GenderEnum['OTHER'], 'O')], default=artist.models.GenderEnum['MALE'], max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('first_release_year', models.CharField(max_length=10)),
                ('no_of_albums_released', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[(artist.models.GenreEnum['RHYTHM_AND_BLUES'], 'rnb'), (artist.models.GenreEnum['COUNTRY'], 'country'), (artist.models.GenreEnum['CLASSIC'], 'classic'), (artist.models.GenreEnum['ROCK'], 'rock'), (artist.models.GenreEnum['JAZZ'], 'jazz')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist')),
            ],
        ),
    ]
