# Generated by Django 5.0.6 on 2024-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='no_of_albums_released',
            field=models.CharField(max_length=3),
        ),
    ]
