# Generated by Django 5.0.6 on 2024-05-23 03:33

import user.manager
import user.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[(user.models.GenderEnum['MALE'], 'M'), (user.models.GenderEnum['FEMALE'], 'F'),
                         (user.models.GenderEnum['OTHER'], 'O')], default=user.models.GenderEnum['MALE'],
                max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
