# Generated by Django 5.0.6 on 2024-05-26 12:00

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(user.models.GenderEnum['MALE'], 'M'), (user.models.GenderEnum['FEMALE'], 'F'), (user.models.GenderEnum['OTHER'], 'O')], default=user.models.GenderEnum['MALE'], max_length=20),
        ),
    ]
